/* Real Chromium integration tests, using only bundled simulated tools. */
const {spawn}=require('node:child_process');
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const assert=require('node:assert/strict');
let playwright;try{playwright=require('playwright');}catch{playwright=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));}
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'verixa-browser-'));
const token='browser-test-token-at-least-24-characters';// signed in as admin with the API key as password
const root=path.resolve(__dirname,'..');
const child=spawn(process.env.PYTHON||'python3',['-m','verixa','--db',path.join(tmp,'state.db'),'serve','--demo','--port','0'],{cwd:root,env:{...process.env,VERIXA_TOKEN:token},stdio:['ignore','pipe','pipe']});
let browser;let checks=0;
async function check(name,fn){await fn();checks++;console.log('PASS '+name);}
(async()=>{
 let stdout='';const url=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Server startup timeout')),10000);child.stdout.on('data',d=>{stdout+=d;const m=stdout.match(/http:\/\/127.0.0.1:\d+/);if(m){clearTimeout(timer);resolve(m[0]);}});child.once('exit',code=>reject(new Error('Server exited '+code)));});
 browser=await playwright.chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.VERIXA_CHROMIUM?{executablePath:process.env.VERIXA_CHROMIUM}:{})});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);
 await check('sign-in screen',async()=>{await page.getByRole('heading',{name:'Sign in.'}).waitFor();assert.equal(await page.locator('#login').isVisible(),true);});
 await page.locator('#login-user').fill('admin');await page.locator('#login-pass').fill('wrong-password');await page.getByRole('button',{name:'Sign in'}).click();
 await check('wrong password rejected',async()=>{await page.waitForFunction(()=>/Wrong username or password/.test(document.querySelector('#login-error').textContent));});
 await page.locator('#login-pass').fill(token);await page.getByRole('button',{name:'Sign in'}).click();await page.locator('#app').waitFor();
 await check('bearer never stored in browser storage',async()=>assert.equal(await page.evaluate(()=>JSON.stringify(sessionStorage)+JSON.stringify(localStorage)).then(x=>x.includes(token)),false));
 await check('overview and live evidence',async()=>{await page.getByRole('heading',{name:'Know what your agent will do.'}).waitFor();assert.equal(await page.locator('.metric strong').first().getAttribute('data-count'),'11');});
 const capture=async name=>{if(process.env.VERIXA_CAPTURE==='1'){fs.mkdirSync(path.join(root,'docs','ux'),{recursive:true});await page.screenshot({path:path.join(root,'docs','ux',name+'.png'),fullPage:true});}};
 await capture('01-overview');
 await page.locator('[data-page=runs]').click();await page.locator('[data-filter=FAIL]').click();
 await page.getByRole('button',{name:'Inspect ↗'}).first().click();await page.waitForFunction(()=>document.querySelector('#detail').open);
 await check('regression evidence',async()=>{assert.equal(await page.locator('#detail .badge.fail').first().textContent(),'FAIL');assert.match(await page.locator('#detail').textContent(),/No policy violations/);});
 await page.locator('#close-detail').click();
 await page.locator('[data-page=scenarios]').click();await page.getByRole('heading',{name:'Small worlds. Real consequences.'}).waitFor();
 await check('ten scenario cards',async()=>assert.equal(await page.locator('#scenario-grid article').count(),10));
 await page.locator('#scenario-search').fill('response lost');
 await check('scenario search',async()=>assert.equal(await page.locator('#scenario-grid article').count(),1));
 await page.getByRole('button',{name:'Rehearse',exact:true}).click();await page.locator('#detail').waitFor();
 await check('refund retry outcome',async()=>assert.equal(await page.locator('#detail .badge.pass').first().textContent(),'PASS'));
 await page.locator('#detail details').first().locator('summary').click();
 await check('trace arguments rendered',async()=>assert.match(await page.locator('#detail pre').first().textContent(),/order-1042/));
 await capture('02-evidence');
 const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Export replay trace'}).click();const dl=await downloadEvent;const tracePath=path.join(tmp,'trace.json');await dl.saveAs(tracePath);
 await check('export trace',async()=>assert.equal(JSON.parse(fs.readFileSync(tracePath)).length,3));
 await page.locator('#close-detail').click();await page.locator('[data-page=runs]').click();
 await page.locator('[data-filter=FAIL]').click();
 await check('verdict filter',async()=>assert.equal(await page.locator('#run-table tbody tr').count(),1));
 await page.getByRole('button',{name:'Replay trace JSON'}).click();await page.locator('#replay-scenario').selectOption('refund-commit-timeout');await page.locator('#trace-file').setInputFiles(tracePath);
 await page.waitForFunction(()=>document.querySelector('#detail-content').textContent.includes('trace-replay'));
 await check('trace replay from console',async()=>assert.equal(await page.locator('#detail .badge.pass').first().textContent(),'PASS'));
 await page.locator('#close-detail').click();await page.locator('[data-page=faults]').click();
 await page.locator('#fault-scenario').selectOption('refund-happy');await page.locator('#fault-tool').selectOption('refund.create');await page.locator('#fault-kind [data-value=commit_timeout]').click();await page.locator('#fault-agent [data-value=regression]').click();
 await capture('03-fault-studio');
 await page.getByRole('button',{name:'Save & rehearse'}).click();await page.waitForFunction(()=>document.querySelector('#detail').open);
 await check('fault studio catches regression',async()=>assert.equal(await page.locator('#detail .badge.fail').first().textContent(),'FAIL'));
 await page.locator('#close-detail').click();await page.locator('[data-page=compare]').click();await page.locator('#baseline').waitFor();
 const ids=await page.evaluate(()=>{const a=Array.from(document.querySelector('#baseline').options);return {b:a.find(x=>x.textContent.includes('Support')&&x.textContent.includes('reference')).value,c:a.find(x=>x.textContent.includes('Support')&&x.textContent.includes('regression')).value};});
 await page.locator('#baseline').selectOption(ids.b);await page.locator('#candidate').selectOption(ids.c);await page.getByRole('button',{name:'Compare outcomes'}).click();await page.locator('#comparison .badge').waitFor();
 await check('release comparison blocks regression',async()=>assert.equal(await page.locator('#comparison .badge').textContent(),'BLOCK'));
 await capture('04-compare');
 await page.locator('[data-page=scenarios]').click();await page.locator('#scenario-search').fill('bounded scale');await page.getByRole('button',{name:'Edit JSON'}).click();
 const scenario=JSON.parse(await page.locator('#scenario-json').inputValue());scenario.id='browser-xss';scenario.name='<img src=x onerror=alert(1)>';await page.locator('#scenario-json').fill(JSON.stringify(scenario));await page.getByRole('button',{name:'Validate & save'}).click();await page.waitForFunction(()=>!document.querySelector('#detail').open);
 await check('imported text escaped',async()=>{await page.getByRole('heading',{name:'<img src=x onerror=alert(1)>'}).waitFor();assert.equal(await page.locator('#scenario-grid img').count(),0);});
 await page.locator('#theme').click();
 await check('dark theme toggle',async()=>assert.equal(await page.locator('html').getAttribute('data-theme'),'dark'));
 await capture('05-dark');
 await page.reload();await page.waitForFunction(()=>document.querySelector('#scenario-grid article'));
 await check('session and theme persistence',async()=>{assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');assert.equal(await page.locator('#login').isVisible(),false);});
 await page.locator('#theme').click();await page.setViewportSize({width:390,height:844});await page.locator('[data-page=overview]').click();
 await check('mobile layout',async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true));
 await capture('06-mobile');
 await page.goto(url+'/#settings');
 await page.locator('#disconnect').click();
 await check('sign out returns to sign-in',async()=>{await page.locator('#login').waitFor();await page.reload();await page.locator('#login').waitFor();assert.equal(await page.locator('#app').isVisible(),false);});
 await check('no browser JavaScript errors',async()=>assert.deepEqual(errors,[]));
 console.log(`${checks} Chromium integration checks passed.`);
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();child.kill('SIGTERM');fs.rmSync(tmp,{recursive:true,force:true});});
